version: '3.7'

services:
        db:
                env_file: ./.env
                image: postgres:11
                environment:
                        - POSTGRES_HOST_AUTH_METHOD=trust
                volumes:
                        - postgres_data:/var/lib/postgresql/data/
        web:
                env_file: ./.env
                build: .
                command: python /core/manage.py runserver 0.0.0.0:8000
                volumes:
                        - .:/core
                ports:
                        - 8000:8000
                depends_on:
                        - db
volumes:
        postgres_data:
